export const propertyList = [
  {
    name: "Antillia",
    image: "/images/propertyone.jpg",
    address: "2699 Green Valley Hollywood",
    priceperMonth: 1500,
    beds: 5,
    bathroom: 2,
    squarefeet: 50 * 40,
    moveinDate: new Date("2022-03-25"),
    location: "NewYork USA",
    type: "Modular",
  },
  {
    name: "The Sloppy House",
    image: "/images/propertytwo.jpg",
    address: "5123 Bell air Hollywood ",
    priceperMonth: 1800,
    beds: 6,
    bathroom: 3,
    squarefeet: 60 * 40,
    moveinDate: new Date("2022-04-20"),
    location: "NewYork USA",
    type: "Modular",
  },
  {
    name: "Antillia",
    image: "/images/propertyone.jpg",
    address: "2699 Green Valley Hollywood ",
    priceperMonth: 1500,
    beds: 5,
    bathroom: 2,
    squarefeet: 50 * 40,
    moveinDate: new Date("2023-03-25"),
    location: "NewYork USA",
    type: "Modular",
  },
  {
    name: "The Sloppy House",
    image: "/images/propertyeight.jpg",
    address: "5123 Bell air Hollywood",
    priceperMonth: 1800,
    beds: 6,
    bathroom: 3,
    squarefeet: 60 * 40,
    moveinDate: new Date("2023-04-20"),
    location: "NewYork USA",
    type: "Modular",
  },
  {
    name: "Tannery Gardens",
    image: "/images/propertythree.jpg",
    address: "6583 Bell air Hollywood ",
    priceperMonth: 1000,
    beds: 3,
    bathroom: 1,
    squarefeet: 20 * 40,
    moveinDate: new Date("2022-04-20"),
    location: "NewYork USA",
    type: "Modular",
  },
  {
    name: "Moore Relaxing",
    image: "/images/propertyfour.jpg",
    address: "7698 Bell air Hollywood ",
    priceperMonth: 3000,
    beds: 8,
    bathroom: 4,
    squarefeet: 70 * 20,
    moveinDate: new Date("2022-04-20"),
    location: "Bell Air California",
    type: "Townhouse",
  },
  {
    name: "Jackdaws",
    image: "/images/propertyfive.jpg",
    address: "11091 Denver ",
    priceperMonth: 2500,
    beds: 6,
    bathroom: 4,
    squarefeet: 20 * 40,
    moveinDate: new Date("2022-04-20"),
    location: "Bell Air California",
    type: "Townhouse",
  },
  {
    name: "Manchester.",
    image: "/images/propertysix.jpg",
    address: "2101 Denver ",
    priceperMonth: 3500,
    beds: 10,
    bathroom: 4,
    squarefeet: 20 * 40,
    moveinDate: new Date("2023-04-20"),
    location: "Bell Air California",
    type: "Townhouse",
  },
  {
    name: "Mulberry",
    image: "/images/propertyseven.jpg",
    address: "7101 Denver ",
    priceperMonth: 3800,
    beds: 10,
    bathroom: 4,
    squarefeet: 100 * 40,
    moveinDate: new Date("2023-04-20"),
    location: "Bell Air California",
    type: "Townhouse",
  },
  {
    name: "Walnut Tree Farm",
    image: "/images/propertyeight.jpg",
    address: "23101 Denver ",
    priceperMonth: 3800,
    beds: 10,
    bathroom: 4,
    squarefeet: 50 * 40,
    moveinDate: new Date("2024-04-20"),
    location: "Houstin Texas",
    type: "Mobile",
  },
  {
    name: "Silverwood",
    image: "/images/propertynine.jpg",
    address: "23101 Denver ",
    priceperMonth: 4800,
    beds: 10,
    bathroom: 4,
    squarefeet: 20 * 80,
    moveinDate: new Date("2024-04-20"),
    location: "Houstin Texas",
    type: "Apartments",
  },
  {
    name: "Farm Hosue",
    image: "/images/propertyten.jpg",
    address: "23101 Denver , Colarado",
    priceperMonth: 4800,
    beds: 10,
    bathroom: 4,
    squarefeet: 60 * 40,
    moveinDate: new Date("2024-04-20"),
    location: "Houstin Texas",
    type: "Apartments",
  },
];
export const Locationoptions = [
  { value: "NewYork USA", label: "NewYork USA" },
  { value: "Bell Air California", label: "Bell Air California" },
  { value: "Houstin Texas", label: "Houstin Texas" },
];
export const moveinoptions = [
  { value: "2022", label: "2022" },
  { value: "2023", label: "2023" },
  { value: "2024", label: "2024" },
];
export const Priceoptions = [
  { value: "500", label: "500 <" },
  { value: "1000", label: "1000<" },
  { value: "1500", label: "1500<" },
  { value: "2000", label: "2000<" },
  { value: "2500", label: "2500<" },
  { value: "5000", label: "5000<" },
];
export const Typenoptions = [
  { value: "Modular", label: "Modular" },
  { value: "Townhouse", label: "Townhouse" },
  { value: "Mobile", label: "Mobile" },
  { value: "Apartments", label: "Apartments" },
];
